.\" $OpenBSD$
.\"
.\" Copyright (c) 2018 joshua stein <jcs@jcs.org>
.\" Copyright (c) 2000 Todd C. Miller <Todd.Miller@courtesan.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: September 11 2015 $
.Dt LOGIN_DURESS 8
.Os
.Sh NAME
.Nm login_duress
.Nd provide duress or standard password authentication type
.Sh SYNOPSIS
.Nm login_duress
.Op Fl s Ar service
.Op Fl v Cm wheel Ns = Ns Cm yes Ns | Ns Cm no
.Op Fl v Cm lastchance Ns = Ns Cm yes Ns | Ns Cm no
.Ar user
.Op Ar class
.Sh DESCRIPTION
The
.Nm
utility is called by
.Xr login 1 ,
.Xr su 1 ,
and others to authenticate the
.Ar user
with passwd-style authentication.
.Pp
The
.Ar user
argument is the login name of the user to be authenticated.
.Pp
The
.Ar service
argument specifies which protocol to use with the
invoking program.
The allowed protocols are
.Em login ,
.Em challenge ,
and
.Em response .
(The
.Em challenge
protocol is silently ignored but will report success as passwd-style
authentication is not challenge-response based).
.Pp
If the
.Cm wheel
argument is specified and is not set to
.Cm yes ,
then the user will be rejected as not being in group
.Dq wheel .
This is used by
.Xr su 1 .
.Pp
If the
.Cm lastchance
argument is specified and is equal to
.Cm yes ,
then if the user's password has expired, and it has not been
expired longer than
.Dq password-dead
seconds (see
.Xr login.conf 5 ) ,
the user will be able to log in one last time to change the password.
.Pp
.Nm
will prompt the user for a password.
If the password supplied matches the user's duress password contained
in
.Pa /etc/duress
instead of the user's system password,
.Nm
will execute the command contained in that file as the user before
reporting successful authentication.
.Sh DATABASE FORMAT
The
.Pa /etc/duress
database should contain one user per line, with the following fields
separated by a colon:
.Pp
.Bl -tag -width password -offset indent -compact
.It name
User's login name.
.It password
User's
.Em encrypted
password.
.It command
User's duress command.
.El
.Pp
The
.Ar password
field can be generated with the
.Xr encrypt 1
utility:
.Bd -literal -offset indent
$ encrypt -b10 -p
.Ed
.Sh FILES
.Bl -tag -width /etc/duress -compact
.It Pa /etc/duress
user database with duress passwords and commands
.El
.Sh SEE ALSO
.Xr encrypt 1 ,
.Xr login 1 ,
.Xr passwd 1 ,
.Xr su 1 ,
.Xr login.conf 5
